name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build the Docker image
        run: |
          ECR_REPOSITORY="443933362940.dkr.ecr.us-west-2.amazonaws.com/todo/todo-server"
          docker build --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} -t "$ECR_REPOSITORY:latest" .

      - name: Push to Amazon ECR
        run: |
          # Push the image to ECR
          docker push "$ECR_REPOSITORY:latest"
